### ISSUE TITLE
Eth1 Simulator has been disabled

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1159]
## Description

#1138 added BLS keystores which take significantly longer to load from disk then the previous SSZ keypairs. This has presented an issue for the eth1-sim where it's taking too long for the validator to read the keypairs so it can't:

- Start the validators quick enough.
- Start the finality, etc checks at the right time.

This is a fairly complicated issue as it involves dealing with async timing problems. That being said, it's very much solvable.

Here's the `.github/workflows/test-suite.yml` except that should be re-added once the sim passes:

```yaml
  eth1-simulator-ubuntu:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
    - uses: actions/checkout@v1
    - name: Install ganache-cli
      run: sudo npm install -g ganache-cli
    - name: Run the beacon chain sim that starts from an eth1 contract
      run: cargo run --release --bin simulator eth1-sim
```
