### ISSUE TITLE
Beacon node exit with code 132 in docker

### ISSUE THREAD

**Issue by bjaq** [sigp/lighthouse#1395]
## Description

When running lighthouse with docker-compose in Ubuntu, my beacon node container exit quickly after starting, with an exit code 132. I see no errors in the logs apart from the docker exit code (see below). Geth and the validator client are running fine. I'm a bit lost. 

![Capture](https://user-images.githubusercontent.com/9341532/88465632-e9399b80-cec4-11ea-8c2e-35edc25d3bca.PNG)

```
beacon_node_1       | Jul 25 19:49:19.292 DEBG Completed batch received                awaiting_batches: 4, blocks: 48, id: 1, service: sync
beacon_node_1       | Jul 25 19:49:19.294 DEBG HTTP API request successful             duration_ms: 0, path: /spec/eth2_config, service: http
beacon_node_1       | Jul 25 19:49:19.300 DEBG Completed batch received                awaiting_batches: 4, blocks: 58, id: 4, service: sync
beacon_node_1       | Jul 25 19:49:19.303 DEBG Requesting batch                        peer: 16Uiu2HAm9phNDb4SXXTDoMJDS2mLCGyf5LLTh6ZyxF8LdiGMTDNf, id: 7, end_slot: 448, start_slot: 384, chain_id: 8780547912560591702, service: sync
validator_client_1  | Jul 25 19:49:19.304 INFO Genesis has already occurred            seconds_ago: 2272754
beacon_node_1       | Jul 25 19:49:19.304 DEBG HTTP API request successful             duration_ms: 0, path: /beacon/genesis_time, service: http
beacon_node_1       | Jul 25 19:49:19.305 DEBG HTTP API request successful             duration_ms: 0, path: /beacon/genesis_validators_root, service: http
beacon_node_1       | Jul 25 19:49:19.305 DEBG Processing batch                        end_slot: 63, start_slot: 0, blocks: 48, id: 1, service: sync
geth_1              | INFO [07-25|19:49:19.308] Upgrading chain index                    type=bloombits percentage=18
geth_1              | INFO [07-25|19:49:19.307] Loaded local transaction journal         transactions=0 dropped=0
geth_1              | INFO [07-25|19:49:19.314] Regenerated local transaction journal    transactions=0 accounts=0
validator_client_1  | Jul 25 19:49:19.322 INFO Loaded validator keypair store          voting_validators: 0
validator_client_1  | Jul 25 19:49:19.325 INFO Block production service started        service: block
validator_client_1  | Jul 25 19:49:19.335 INFO Attestation production service started  next_update_millis: 9664, service: attestation
geth_1              | INFO [07-25|19:49:19.360] Allocated fast sync bloom                size=512.00MiB
geth_1              | ERROR[07-25|19:49:19.523] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
geth_1              | ERROR[07-25|19:49:19.523] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
geth_1              | ERROR[07-25|19:49:19.524] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=3 err="failed to initialize libusb: libusb: unknown error [code -99]"
geth_1              | INFO [07-25|19:49:19.590] New local node record                    seq=12 id=821ecfdc008da69a ip=127.0.0.1 udp=30303 tcp=30303
geth_1              | INFO [07-25|19:49:19.617] Started P2P networking                   self=enode://f9b2771aeab9bc0dfc773916a1d7084888e9bb94e0f106ec685fd869672fb5d092fb224bd4223a8089c1cf9c5407c68a932a3fa6675234af8ea6cb63e7f4d310@127.0.0.1:30303
geth_1              | INFO [07-25|19:49:19.649] IPC endpoint opened                      url=/root/.ethereum/goerli/geth.ipc
geth_1              | INFO [07-25|19:49:19.679] HTTP endpoint opened                     url=http://[::]:8545/               cors= vhosts=*
lighthouse-docker_beacon_node_1 exited with code 132
geth_1              | INFO [07-25|19:49:27.397] Initializing fast sync bloom             items=1763753 errorrate=0.000 elapsed=8.014s
geth_1              | INFO [07-25|19:49:27.450] Upgrading chain index                    type=bloombits percentage=21
geth_1              | INFO [07-25|19:49:29.625] Block synchronisation started
geth_1              | INFO [07-25|19:49:29.943] Disabling direct-ancient mode            origin=3109919 ancient=2818047
geth_1              | INFO [07-25|19:49:30.020] Imported new block headers               count=65 elapsed=39.546ms number=3110009 hash="4448ed…b29e43" ignored=25
geth_1              | INFO [07-25|19:49:30.043] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=555.87B throttle=8192
geth_1              | INFO [07-25|19:49:30.048] Imported new block receipts              count=3  elapsed="313.016µs" number=3109922 hash="9dc0e5…160134" age=22m18s  size=1.79KiB
geth_1              | INFO [07-25|19:49:30.161] Imported new block receipts              count=23 elapsed=9.066ms     number=3109945 hash="54b52f…89191e" age=16m33s  size=59.57KiB
geth_1              | INFO [07-25|19:49:30.297] Imported new state entries               count=17 elapsed="2.3µs"     processed=9496404 pending=241 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:31.241] Looking for peers                        peercount=2 tried=18 static=0
geth_1              | INFO [07-25|19:49:31.668] New local node record                    seq=13 id=821ecfdc008da69a ip=20.43.35.139 udp=30303 tcp=30303
geth_1              | INFO [07-25|19:49:31.753] Imported new state entries               count=241 elapsed="3.3µs"     processed=9496645 pending=1636 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:32.733] Imported new state entries               count=384 elapsed="2.7µs"     processed=9497029 pending=6470 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:33.190] Imported new state entries               count=774 elapsed="965.55µs"  processed=9497803 pending=7903 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:33.434] Imported new state entries               count=421 elapsed="948.349µs" processed=9498224 pending=8227 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:34.028] Imported new state entries               count=1480 elapsed=4.263ms     processed=9499704 pending=7971 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:34.280] Imported new state entries               count=384  elapsed=1.486ms     processed=9500088 pending=8211 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:34.501] Imported new state entries               count=384  elapsed=2.226ms     processed=9500472 pending=8403 retry=0 duplicate=0 unexpected=0
geth_1              | INFO [07-25|19:49:34.891] Imported new state entries               count=1152 elapsed=4.103ms     processed=9501624 pending=8554 retry=0 duplicate=0 unexpected=0
validator_client_1  | Jul 25 19:49:35.009 ERRO Unable connect to beacon node           error: ReqwestError(reqwest::Error { kind: Request, url: "http://beacon_node:5052/node/syncing", source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Other, error: "failed to lookup address information: Name or service not known" })) }), service: notifier
```

I'm also running a mainnet and ropsten nodes on the same VM, but I changed the ports in the docker-compose.yml to avoid any conflicts.

Here is the docker-compose.yml :

```
version: "3.0"

services:
    beacon_node:
        image: sigp/lighthouse:latest
        volumes:
            - ./.lighthouse:/root/.lighthouse
            - ./scripts:/root/scripts
            - ./network:/root/network
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
    validator_client:
        image: sigp/lighthouse:latest
        volumes:
            - ./.lighthouse:/root/.lighthouse
            - ./scripts:/root/scripts
        depends_on:
            - beacon_node
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
    geth:
        build:
            context: geth
        volumes:
            - geth:/root/.ethereum
            - ./scripts:/root/scripts
        env_file: .env
        ports:
            - 30305:30305/tcp
            - 30305:30305/udp

volumes:
    geth:

```

## Version

I'm running the latest docker image within Ubuntu 18.04 on an azure VM.

I followed the instructions on this page : https://lighthouse-book.sigmaprime.io/become-a-validator-docker.html
