### ISSUE TITLE
Graffiti ""

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/lighthouse#2054]
## Description

`--graffiti=""` results in graffiti of `""` which seems strange when setting it as a flag in docker compose file.

## Version

Docker 1.0.3

## Present Behaviour

`--graffiti=""` results in graffiti of `""`

## Expected Behaviour

`--graffiti=""` results in no graffiti

## Steps to resolve

I'm actually not sure how to just set a blank graffiti without using a flag that does other things too?

**Comment by michaelsproul** [comment]
Hmm, I can't reproduce this locally so I'm wondering if there's something peculiar about your setup that's causing this.

1. What shell are you using? Both shells I tried (`fish` and `bash`) strip the quotes from the string before passing it to Lighthouse. i.e. they treat `--graffiti=""` exactly the same as `--graffiti=` (the latter here could be a workaround for you).
2. Are you sure you're not using smart quotes, like `“”`? These often get auto-inserted in various editors/browsers, but are not compatible with the shell.

**Comment by MysticRyuujin** [comment]
Are you running it via Docker-Compose file? I typed the quotes myself so I know they're real quotes :)

```
version: "3.3"
services:
  lh-beacon:
    container_name: lh-beacon
    image: "sigp/lighthouse:v1.0.3"
    ports:
      - "5052:5052" # RESTful HTTP API server
      - "5053:5053" # WebSocket
      - "9000:9000" # Peering
      - "9000:9000/udp" # Peering
    volumes:
      - "/data/dockerfiles/lh-beacon:/root/.lighthouse"
    stop_signal: SIGINT
    stop_grace_period: 2m
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    command:
      - lighthouse
      - --network=mainnet
      - beacon_node
      - --slasher
      - --disable-upnp
      - --eth1
      - --http
      - --http-address=0.0.0.0
      - --metrics
      - --metrics-address=0.0.0.0
      - --ws
      - --ws-address=0.0.0.0
      - --target-peers=100
      - --eth1-endpoints=<redacted>
      - --graffiti=""
```
