### ISSUE TITLE
Publish the ssz crate to crates.io via CI

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2259]
## Description

I own the [`eth2_ssz`](https://crates.io/crates/eth2_ssz) crate which has a very outdated version of SSZ.

It would be nice to add something to CI to ensure that we keep that crate updated whenever we merge to `stable`. I could quite easily create an additional owner for the crate and then add their credentials to CI.

**Comment by michaelsproul** [comment]
One difficulty with auto-publishing crates is determining when they've changed "enough" to require a version bump/republish. And I think the version bump needs to be done manually (it needs to already be set in the `Cargo.toml` before attempting to publish). So far the best I can come up with is this:

1. Have a job on CI that detects code changes to the crate in question and _fails_ if the code is changed without the version being changed. The choice of version change is up to the committer, could be patch/minor/major. We could have scripts to assist with this version bumping process.
2. When code is merged to `stable`, publish any crate whose published version is older than its current version.

One flaw in this scheme is that it might force version skips (unless we publish upon any merge to `unstable`). e.g. change code, bump to `v1.1.1`, change again, bump to `v1.1.2`, merge to `stable`: published version jumps `v1.1.0` to `v1.1.2`.

**Comment by paulhauner** [comment]
Hey @realbigsean, would you be interested in this one when you have some spare time? We'd probably want to publish `ssz_types` as well.

**Comment by paulhauner** [comment]
Also, I wonder if @sorpaas would be open to us taking over the [`ssz`](https://crates.io/crates/ssz) crate? :pray: I get the feeling that it's not being updated anymore and I'm not sure if it's compatible with the production version of the SSZ spec.

**Comment by realbigsean** [comment]
Can do!

**Comment by michaelsproul** [comment]
If anyone is interested in working around this in the meantime, you can do so using `patch` and `git` dependencies:

```toml
[package]
name = "my_package"
version = "0.1.0"
edition = "2018"

[dependencies]
types = { git = "https://github.com/sigp/lighthouse", branch = "stable" }

[patch]
[patch.crates-io]
tree_hash = { git = "https://github.com/sigp/lighthouse", branch = "stable" }
tree_hash_derive = { git = "https://github.com/sigp/lighthouse", branch = "stable" }
eth2_ssz = { git = "https://github.com/sigp/lighthouse", branch = "stable" }
eth2_ssz_derive = { git = "https://github.com/sigp/lighthouse", branch = "stable" }
eth2_ssz_types = { git = "https://github.com/sigp/lighthouse", branch = "stable" }
eth2_hashing = { git = "https://github.com/sigp/lighthouse", branch = "stable" }

```
