### ISSUE TITLE
Slasher Database Errors (MapFull)

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/lighthouse#2538]
## Description

Beacon Node throwing errors about slasher service and pruning of slasher database

## Version

Docker image `v1.5.0` (I also saw this in `v1.4.0`)

## Present Behaviour

I get a steady stream of errors related to the slasher service:
```
Aug 24 20:48:11.729 ERRO Error during slasher database pruning   error: DatabaseError(MapFull), epoch: 59979, service: slasher
Aug 24 20:48:25.437 ERRO Error processing array update           error: DatabaseError(MapFull), service: slasher
Aug 24 20:48:25.441 ERRO Error during scheduled slasher processing, error: DatabaseError(MapFull), epoch: 59979, service: slasher
...
Aug 24 20:48:50.141 ERRO Error during slasher database pruning   error: DatabaseError(MapFull), epoch: 59979, service: slasher
Aug 24 20:49:04.834 ERRO Error processing array update           error: DatabaseError(MapFull), service: slasher
Aug 24 20:49:04.837 ERRO Error during scheduled slasher processing, error: DatabaseError(MapFull), epoch: 59979, service: slasher
```

## Expected Behaviour

No errors?

## Steps to resolve

I have two servers, both running via docker, both with the same behavior...

Here is my sanitized `docker-compose.yaml` (`<redacted>`)
```
version: "3.4"

services:
  lh-beacon:
    container_name: lh-beacon
    image: "sigp/lighthouse:v1.5.0"
    volumes:
      - "/data/volumes/lh-beacon:/root/.lighthouse"
    ports:
      - "9000:9000" # Peering (TCP)
      - "9000:9000/udp" # Peering (UDP)
    restart: unless-stopped
    command:
      - lighthouse
      - beacon_node
      # FLAGS
      - --disable-upnp
      - --eth1
      - --http
      - --metrics
      - --slasher
      - --subscribe-all-subnets
      - --import-all-attestations
      - --validator-monitor-auto
      # OPTIONS
      - --monitoring-endpoint=<redacted>
      - --eth1-endpoints=<redacted>
      - --http-address=0.0.0.0
      - --http-allow-origin=*
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --network=mainnet
      - --port=9000
      - --target-peers=50
      - --slasher-broadcast
      - --libp2p-addresses=<redacted>
      - --trusted-peers=<redacted>
      - --validator-monitor-pubkeys=<redacted>
    logging:
      driver: "local"
```

This is a really powerful server, plenty of RAM, plenty of disk space. I assume this has something to do with trying to run a slasher subscribed to all subnets or something? I would think this should be a possible setup?

OS is `Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-80-generic x86_64)`

```bash
# docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
