### ISSUE TITLE
Use a --config-file and config.yaml for input configurations

### ISSUE THREAD

**Issue by Autoparallel** [sigp/lighthouse#3778]
## Description

Providing inputs via the CLI works, but it is easier to manage via a `config.yaml` file since the file is editable and since it can be point to for `systemd`.  This issue mimics that posed for Erigon in [this issue](https://github.com/ledgerwatch/erigon/issues/4863). Prysm also follows this same implementation. I think that having standardized configs would be very helpful for node builders.

## Outline

Rather than provide 
```
lighthouse bn \
  --network mainnet \
  --execution-endpoint http://localhost:8551 \
  --execution-jwt /home/user/datadir/jwt.hex \
  --checkpoint-sync-url https://mainnet.checkpoint.sigp.io \
  --disable-deposit-contract-sync \ 
  --datadir /home/user/datadir
```
in the CLI, instead we can create `config.yaml` with
```yaml
  network: "mainnet"
  execution-endpoint: "http://localhost:8551" 
  execution-jwt: "/home/user/datadir/jwt.hex"
  checkpoint-sync-url: "https://mainnet.checkpoint.sigp.io"
  disable-deposit-contract-sync: true
  datadir: "/home/user/datadir"
```
Then it is just a matter of running `lighthouse bn --config-file ./config.yaml`.

## Final Comments

I am happy to attempt to add this feature, but I am not as familiar with the codebase as others. It may be much easier for a familiar face to tackle this quickly.
