### ISSUE TITLE
Low peer count on Gnosis

### ISSUE THREAD

**Issue by vandot** [sigp/lighthouse#4490]
## Description

I have one pair of nodes (Nethermind + Lighthouse) for Sepolia and it's running flawlessly. High number of connected peers and  `/lighthouse/nat` returns `{"data":true}`
On the other hand I have three pair of nodes (Nethermind + Lighthouse) for Gnosis and there is an issue with low peer count.  `/lighthouse/nat` returns `{"data":false}`

Configs and versions are the same for all nodes, of course except `--network=sepolia` and `--network=gnosis` and all nodes are synced.

## Version

Lighthouse -> `v4.3.0`
Nethermind -> `1.19.3`

## Present Behaviour

All nodes are running on the same EKS (AWS k8s) cluster with enabled wide range of TCP and UDP ports. Using telnet and nmap shows that all ports are open, but only sepolia node  returns `{"data":true}` on `/lighthouse/nat` endpoint.

Nodes are deployed using latest (1.0.5) [lighthouse Helm chart](https://github.com/ethpandaops/ethereum-helm-charts/tree/master/charts/lighthouse)
Notable part of `values.yaml`
```
mode: "beacon"

p2pNodePort:
  enabled: true

extraArgs:
  - --network=gnosis
  - --execution-endpoint=http://gnosis-nethermind:8551
  - --validator-monitor-auto
  - --subscribe-all-subnets
  - --import-all-attestations

checkpointSync:
  enabled: true
  url: "https://checkpoint.gnosischain.com/"
```

Command used to start gnosis node
```
lighthouse beacon_node --datadir=/data --disable-upnp --disable-enr-auto-update --enr-address=$EXTERNAL_IP --enr-tcp-port=$EXTERNAL_PORT --enr-udp-port=$EXTERNAL_PORT --listen-address=0.0.0.0 --port=
9000 --discovery-port=9000 --http --http-address=0.0.0.0 --http-port=5052 --execution-jwt=/data/jwt.hex --metrics --metrics-address=0.0.0.0 --metrics-port=5054 --checkpoint-sync-url=https://checkpoint.gnosischain.com/ --network=gnos
is --execution-endpoint=http://gnosis-nethermind:8551 --validator-monitor-auto --subscribe-all-subnets --import-all-attestations
```
Command used to start sepolia node
```
lighthouse beacon_node --datadir=/data --disable-upnp --disable-enr-auto-update --enr-address=$EXTERNAL_IP --enr-tcp-port=$EXTERNAL_PORT --enr-udp-port=$EXTERNAL_PORT --listen-address=0.0.0.0 --port=
9000 --discovery-port=9000 --http --http-address=0.0.0.0 --http-port=5052 --execution-jwt=/data/jwt.hex --metrics --metrics-address=0.0.0.0 --metrics-port=5054 --checkpoint-sync-url=https://sepolia.checkpoint-sync.ethpandaops.io/ --
network=sepolia --execution-endpoint=http://sepolia-nethermind:8551 --validator-monitor-auto --subscribe-all-subnets --import-all-attestations
```

`EXTERNAL_IP` and `EXTERNAL_PORT` are properly set and used.

## Expected Behaviour

Both sepolia and gnosis Lighthouse should return `{"data":true}` on `/lighthouse/nat` endpoint and have high number of connected (inbound and outbound) peers.
