### ISSUE TITLE
Deploy book via CI

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#546]
## Description

In `/book` there is an mdbook containing our hand-written documentation (note: this is distinct to the [rust docs](http://lighthouse-docs.sigmaprime.io/)).

The book is presently deployed at http://lighthouse-book.sigmaprime.io/ 

I deployed it from my local machine (with the same credentials as the ci server) using:

```
aws s3 sync book/book/ s3://lighthouse-book.sigmaprime.io/ --exclude '.lock' --delete
```

Over at #543 I have modified the `Dockerfile` and `gitlab-ci.yaml` in an attempt to get it to deploy via gitlab CI (just like the rust docs do). I'm getting a credentials error at the moment.

The notable changes to the `Dockerfile` are:
- Add `RUN cargo install mdbook`: installs the binary crate that builds the book.
- Remove `git-lfs` (it's no longer required on master)

For `gitlab-ci.yaml`, this is what I have added. It seems to work, it just fails on credentials:

```yaml
build-book:
  stage: document
  script:
    - mdbook build book
    - aws s3 sync book/book/ s3://lighthouse-book.sigmaprime.io/ --exclude '.lock' --delete
  only:
   - master

```
