### ISSUE TITLE
Issue: Lighthouse Node Returns 404 Error When Querying Validator Attestation Rewards

### ISSUE THREAD

**Issue by xueqianLu** [sigp/lighthouse#7193]
#### Description
When using the latest versions of Lighthouse, Teku, Prysm, and Geth to build a multi client version PoS testnet,  the Lighthouse node returns a `404 NOT_FOUND` error when attempting to query validator rewards for attestations. Specifically, the error message indicates that the state at a particular slot is missing.

#### Steps to Reproduce
1. Set up the network using the provided `network_params.yml`:
   ```yaml
   participants:
     - el_type: besu
       cl_type: prysm
       validator_count: 86

     - el_type: geth
       cl_type: lighthouse
       validator_count: 85
     - el_type: geth
       cl_type: teku
       validator_count: 85

   mev_type: null

   network_params:
   deneb_fork_epoch: 0
   seconds_per_slot: 3
   num_validator_keys_per_node: 32
   ```
2. Start the network using the Kurtosis CLI:
   ```bash
   $ kurtosis run --enclave test github.com/ethpandaops/ethereum-package --args-file network_params.yml
   ```
3. Wait for the network to progress to 7-8 epochs.
4. Query the validator rewards for epoch 1 using the following command (replace `32921` with the actual port of the Lighthouse node's 4000 service):
   ```bash
   curl -X 'POST' 'http://127.0.0.1:32921/eth/v1/beacon/rewards/attestations/1' \
     -H 'accept: application/json' \
     -H 'Content-Type: application/json' \
     -d '["1","2","3"]'
   ```

#### Behavior
The Lighthouse node returns a `404 NOT_FOUND` error:
```json
{"code":404,"message":"NOT_FOUND: missing state at slot 95","stacktraces":[]}
```

#### Environment
- **Ethereum-Packages Version**: Latest (as of the issue date)
- **CL Clients Used**: Lighthouse, Teku, Prysm
- **EL Clients Used**: Besu, Geth
- **Network Configuration**: `network_params.yml` as provided
- **Kurtosis Version**: 1.4.3
